### ISSUE TITLE
This tool downloaded a suspicious file.

### ISSUE THREAD

**Issue by putuoka** [shubham8550/vicuna-ts#2]
<img width="557" alt="image" src="https://github.com/shubham8550/vicuna-ts/assets/20880839/dcc95f7b-b707-4adb-a73f-56aeaf6bd941">

**Comment by shubham8550** [comment]
it is  https://github.com/ggerganov/llama.cpp LLAMA CPP binary  if you don't wanna use the existing one u can compile one yourself and specify the binary location "executablePath" in the constructor
